# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{escoffier}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Erik Kastman"]
  s.date = %q{2010-04-26}
  s.description = %q{Administrative prep tasks, from mother sauces to hotel pans.}
  s.email = %q{ekk@medicine.wisc.edu}
  s.executables = ["normalize_directory.rb", "mise"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "Manifest.txt",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "bin/mise",
     "bin/normalize_directory.rb",
     "escoffier.gemspec",
     "lib/escoffier.rb",
     "lib/escoffier/compressible.rb",
     "lib/escoffier/core_additions.rb",
     "lib/escoffier/normalizer.rb",
     "lib/escoffier/smepable.rb",
     "spec/escoffier_spec.rb",
     "spec/normalizer_spec.rb",
     "spec/smepable_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "tasks/rspec.rake"
  ]
  s.homepage = %q{http://github.com/kastman/escoffier}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Mise en Place Prep Tasks}
  s.test_files = [
    "spec/escoffier_spec.rb",
     "spec/spec_helper.rb",
     "spec/normalizer_spec.rb",
     "spec/smepable_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bzip2-ruby>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<bzip2-ruby>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<bzip2-ruby>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

